### ISSUE TITLE
Bug in QGIS

### ISSUE THREAD

**Issue by fbobilliermonnot** [stefaneichert/OpenLidarToolbox#1]
I have that bug in QGIS with OpenLidarToolbox : 

"C:/Users/stagiaire.ILEXGRAF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\open_lidar_tools\algorithms\create_dfm.py", line 61, in initAlgorithm
fileFilter='Lidar Files (*.las *.laz)', defaultValue=None))
TypeError: 'fileFilter' is an unknown keyword argument

What can i do ?

**Comment by stefaneichert** [comment]
Hi! Thank you for reporting this bug. Could you please let us know which operating system you use and which version of QGIS?
We will then try to reproduce the bug and fix it.
Best regards,
Stefan

**Comment by fbobilliermonnot** [comment]
Hello,

The version of QGIS is 3.4.7-Madeira and 21H1 for Windows adn 2.1 for OpenLiDAR Toolbox
![1](https://user-images.githubusercontent.com/91545268/136023554-94c32b09-5a8b-4818-aabe-95f29f33c9ed.PNG)

![2](https://user-images.githubusercontent.com/91545268/136023684-d5513521-a4ed-4e34-9e9f-62e90f6968a9.PNG)

Thanks a lot.

Have a good day

**Comment by stefaneichert** [comment]
I suppose this bug is caused by Qgis 3.4.7 which is a very early pre release version. The plugin is tested on the current official releases and once Qgis 3.4. is a stable release, we will implement the plugin for this version too.
With the next version of OpenLidartoolbox which is in development, we will take a closer look at this. 
For the time being, I can only suggest you use the official stable release of QGIS and test, if the bug does occur there too.
Best regards, Stefan
